### ISSUE TITLE
Could you add Regions and put Query and Part into 2 different files?

### ISSUE THREAD

**Issue by TBZ-BenjaminJacober** [Jeet-Chugh/pcpartscraper#1]
Ive done this for myself, sadly i dont know where i can send a push request. (Normally using GitLab)
Great package, saved me some time. Thanks mate. 

👍

**Comment by Jeet-Chugh** [comment]
Hey there, thanks for suggesting!  However I would like to keep the format that is provided, because since both modules run hand-in-hand, I would like to retain them in one file. If you figure out how to push  to GitHub, I will check it out, and might push it to the master branch. Thanks!
