### ISSUE TITLE
Yesterday I got IP banned from PCPP.

### ISSUE THREAD

**Issue by thefakequake** [Jeet-Chugh/pcpartscraper#3]
This is totally my fault, but what do you recommend I do to prevent this from happening in the future? Now I have to use a VPN to access PCPP, but it's not a big deal.

**Comment by Jeet-Chugh** [comment]
Hey QuaKE8782,
I thinks that it's pretty odd that you got banned from PCPP, as I have been testing this for months, and I still have access to the site. I think that if you send too many requests without completing the CAPTCHA (which I have not been able to bypass), then it may IP Ban you.

I would be on the lookout in the next few days if PCPP finally allows you to visit the site, as that is what happens to most people. Unfortunately, there is little that I can do to make PCPartScraper immune to this, as Cloudflare does an exceptional job at protecting their sites.

So my advise is to use the API until you see None as the results. Then you should go to pcpartpicker.com and fill out the CAPTCHA and wait.

- Jeet
