### ISSUE TITLE
Query is broken

### ISSUE THREAD

**Issue by thefakequake** [Jeet-Chugh/pcpartscraper#4]
When I make a query for anything it returns None but when I go on PCPP and search it up its there.

**Comment by Jeet-Chugh** [comment]
Hey Quake,

could you provide me with a screenshot of what happened?
Does PCPP ask for CloudFlare authentication when you tried to go to the link manually?
Thanks!

**Comment by thefakequake** [comment]
I switched to my own custom scraper after that incident. Thank you so much for your help though. It wasn't asking for authentication or anything, the scraper just stopped returning products correctly.
